import type { Metadata } from "next";
import { Black_Ops_One} from "next/font/google"
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";

const BOO = Black_Ops_One({
  subsets: ['latin'],
  weight: ['400']

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={BOO.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
